# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Dict, List, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .create_product import CreateProduct
from .create_product_group import CreateProductGroup
from .get_domains import GetDomains
from .get_product_descendants import GetProductDescendants
from .get_projects import GetProjects
from .input_types import ProductAdd
from .login import Login
from .who_am_i import WhoAmI


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def get_domains(self, **kwargs: Any) -> GetDomains:
        query = gql(
            """
            query GetDomains {
              domains {
                id
                name
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetDomains", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetDomains.model_validate(data)

    async def login(
        self,
        username: str,
        password: str,
        domain_name: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> Login:
        query = gql(
            """
            mutation Login($domainName: String, $username: String!, $password: String!) {
              login(domainName: $domainName, username: $username, password: $password) {
                id
                nbf
                exp
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "domainName": domain_name,
            "username": username,
            "password": password,
        }
        response = await self.execute(
            query=query, operation_name="Login", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Login.model_validate(data)

    async def get_projects(self, **kwargs: Any) -> GetProjects:
        query = gql(
            """
            query GetProjects {
              projects {
                id
                code
                title
                doneAt
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="GetProjects", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return GetProjects.model_validate(data)

    async def get_product_descendants(
        self,
        project_id: Any,
        ancestor_ids: List[Any],
        max_depth: Union[Optional[int], UnsetType] = UNSET,
        **kwargs: Any
    ) -> GetProductDescendants:
        query = gql(
            """
            query GetProductDescendants($projectId: UUID!, $ancestorIds: [UUID!]!, $maxDepth: Int) {
              productDescendants(
                projectId: $projectId
                ancestorIds: $ancestorIds
                includeAncestors: true
                filter: {tagsInclude: [], tagsExclude: []}
                maxDepth: $maxDepth
              ) {
                kind
                id
                code
                parentId
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "projectId": project_id,
            "ancestorIds": ancestor_ids,
            "maxDepth": max_depth,
        }
        response = await self.execute(
            query=query,
            operation_name="GetProductDescendants",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetProductDescendants.model_validate(data)

    async def create_product_group(
        self, product: ProductAdd, **kwargs: Any
    ) -> CreateProductGroup:
        query = gql(
            """
            mutation CreateProductGroup($product: ProductAdd!) {
              productCreate(product: $product) {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {"product": product}
        response = await self.execute(
            query=query,
            operation_name="CreateProductGroup",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CreateProductGroup.model_validate(data)

    async def create_product(self, product: ProductAdd, **kwargs: Any) -> CreateProduct:
        query = gql(
            """
            mutation CreateProduct($product: ProductAdd!) {
              productCreate(product: $product) {
                id
              }
            }
            """
        )
        variables: Dict[str, object] = {"product": product}
        response = await self.execute(
            query=query, operation_name="CreateProduct", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateProduct.model_validate(data)

    async def who_am_i(self, **kwargs: Any) -> WhoAmI:
        query = gql(
            """
            query WhoAmI {
              whoami {
                id
                nbf
                exp
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="WhoAmI", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return WhoAmI.model_validate(data)
