# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class CreateProductGroup(BaseModel):
    product_create: "CreateProductGroupProductCreate" = Field(alias="productCreate")


class CreateProductGroupProductCreate(BaseModel):
    id: Any


CreateProductGroup.model_rebuild()
