# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class CreateProduct(BaseModel):
    product_create: "CreateProductProductCreate" = Field(alias="productCreate")


class CreateProductProductCreate(BaseModel):
    id: Any


CreateProduct.model_rebuild()
