# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from .base_model import BaseModel


class Domains(BaseModel):
    domains: List["DomainsDomains"]


class DomainsDomains(BaseModel):
    id: int
    name: str


Domains.model_rebuild()
