# Generated by ariadne-codegen
# Source: schema.graphql

from enum import Enum


class ChunksOrderField(str, Enum):
    TITLE = "TITLE"
    ESTIMATION_SUM = "ESTIMATION_SUM"
    SPENT_SUM = "SPENT_SUM"
    PRIORITY = "PRIORITY"
    STATUS = "STATUS"
    UPDATED_AT = "UPDATED_AT"


class EpicStatusEnum(str, Enum):
    BACKLOG = "BACKLOG"
    TODO = "TODO"
    WIP = "WIP"
    HOLD = "HOLD"
    DONE = "DONE"
    OMIT = "OMIT"


class ProductKind(str, Enum):
    GROUP = "GROUP"
    PRODUCT = "PRODUCT"


class ProductStatusEnum(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"


class ProductsOrderField(str, Enum):
    CODE = "CODE"
    ESTIMATION_SUM = "ESTIMATION_SUM"
    SPENT_SUM = "SPENT_SUM"
    STATUS = "STATUS"
    UPDATED_AT = "UPDATED_AT"


class QueueStatus(str, Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ReportsOrderField(str, Enum):
    REPORT_DATE = "REPORT_DATE"
    CREATED_AT = "CREATED_AT"
    UPDATED_AT = "UPDATED_AT"


class SprintsOrderField(str, Enum):
    TITLE = "TITLE"
    START_AT = "START_AT"
    END_AT = "END_AT"
    COMPLETED = "COMPLETED"
    CREATED_AT = "CREATED_AT"
    UPDATED_AT = "UPDATED_AT"


class TaskStatusEnum(str, Enum):
    BACKLOG = "BACKLOG"
    TODO = "TODO"
    WIP = "WIP"
    HOLD = "HOLD"
    DONE = "DONE"


class UserRole(str, Enum):
    EDITOR = "EDITOR"
    REPORTER = "REPORTER"
    MANAGER = "MANAGER"
    REPORT_AUDITOR = "REPORT_AUDITOR"
