# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetProjects(BaseModel):
    projects: List["GetProjectsProjects"]


class GetProjectsProjects(BaseModel):
    id: Any
    code: str
    title: str
    done_at: Optional[Any] = Field(alias="doneAt")


GetProjects.model_rebuild()
