# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ProductKind


class GetProductDescendants(BaseModel):
    product_descendants: List["GetProductDescendantsProductDescendants"] = Field(
        alias="productDescendants"
    )


class GetProductDescendantsProductDescendants(BaseModel):
    kind: ProductKind
    id: Any
    code: str
    parent_id: Optional[Any] = Field(alias="parentId")


GetProductDescendants.model_rebuild()
