# Generated by ariadne-codegen
# Source: queries.graphql

from typing import List

from .base_model import BaseModel


class GetDomains(BaseModel):
    domains: List["GetDomainsDomains"]


class GetDomainsDomains(BaseModel):
    id: int
    name: str


GetDomains.model_rebuild()
