# Generated by ariadne-codegen
# Source: schema.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel, Upload
from .enums import (
    ChunksOrderField,
    EpicStatusEnum,
    ProductKind,
    ProductsOrderField,
    ProductStatusEnum,
    ReportsOrderField,
    UserRole,
)


class AssignmentAdd(BaseModel):
    task_id: Any = Field(alias="taskId")
    user_id: Any = Field(alias="userId")


class AssignmentChange(BaseModel):
    hours_in_day: Optional[int] = Field(alias="hoursInDay", default=None)


class AuditUserTeamChange(BaseModel):
    joined_at: Optional[Any] = Field(alias="joinedAt", default=None)
    team_id: Optional[Any] = Field(alias="teamId", default=None)


class ChunksChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: Optional[str] = None
    description: Optional[Any] = None
    priority: Optional[int] = None
    estimation: Optional[int] = None


class ChunksOrder(BaseModel):
    field: ChunksOrderField
    ascending: bool


class EpicAdd(BaseModel):
    project_id: Any = Field(alias="projectId")
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: str
    description: Any
    estimation: Optional[int] = None
    priority: Optional[int] = None
    status: EpicStatusEnum
    users: List[Any]
    products: List[Any]


class EpicChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: Optional[str] = None
    description: Optional[Any] = None
    estimation: Optional[int] = None
    priority: Optional[int] = None
    status: Optional[EpicStatusEnum] = None
    users: Optional["UuidsUpdate"] = None
    products: Optional[List[Any]] = None


class EpicGroupAdd(BaseModel):
    project_id: Any = Field(alias="projectId")
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: str
    description: Any
    priority: Optional[int] = None
    estimation: Optional[int] = None


class EpicGroupChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: Optional[str] = None
    description: Optional[Any] = None
    priority: Optional[int] = None
    estimation: Optional[int] = None


class PostAdd(BaseModel):
    project_id: Any = Field(alias="projectId")
    product_ids: List[Any] = Field(alias="productIds")
    description: Any
    tags: List[str]
    uploads: List[Upload]


class PostAddBlind(BaseModel):
    user_id: Any = Field(alias="userId")
    project_code: str = Field(alias="projectCode")
    product_paths: List[str] = Field(alias="productPaths")
    description: Any
    tags: List[str]
    uploads: List[Upload]


class PostChange(BaseModel):
    product_ids: Optional[List[Any]] = Field(alias="productIds", default=None)
    description: Optional[Any] = None
    tags: Optional[List[str]] = None
    uploads: List[Upload]
    delete_media: List[Any] = Field(alias="deleteMedia")
    media_order: List[Any] = Field(alias="mediaOrder")


class PostsCursor(BaseModel):
    last_time: Any = Field(alias="lastTime")
    last_id: Any = Field(alias="lastId")


class PostsInputFilter(BaseModel):
    project_id: Optional[Any] = Field(alias="projectId", default=None)
    product_ids: List[Any] = Field(alias="productIds")
    chunk_ids: List[Any] = Field(alias="chunkIds")
    user_ids: List[Any] = Field(alias="userIds")
    description: Optional[str] = None
    post_tags_include: Optional[List[str]] = Field(
        alias="postTagsInclude", default=None
    )
    post_tags_exclude: Optional[List[str]] = Field(
        alias="postTagsExclude", default=None
    )
    product_tags_include: Optional[List[str]] = Field(
        alias="productTagsInclude", default=None
    )
    product_tags_exclude: Optional[List[str]] = Field(
        alias="productTagsExclude", default=None
    )


class PostsInputPagination(BaseModel):
    after: Optional["PostsCursor"] = None
    limit: int


class ProductAdd(BaseModel):
    project_id: Any = Field(alias="projectId")
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    code: str
    kind: ProductKind
    description: Any
    thumbnail: Optional[Upload] = None
    deliverable: Optional[bool] = None
    status: Optional[ProductStatusEnum] = None
    due_to: Optional[Any] = Field(alias="dueTo", default=None)
    estimation: Optional[int] = None
    tags: List[str]


class ProductChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    code: Optional[str] = None
    description: Optional[Any] = None
    thumbnail: Optional[Upload] = None
    deliverable: Optional[bool] = None
    status: Optional[ProductStatusEnum] = None
    due_to: Optional[Any] = Field(alias="dueTo", default=None)
    estimation: Optional[int] = None
    tags: Optional["StringsUpdate"] = None


class ProductCommonChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    code: Optional[str] = None
    description: Optional[Any] = None
    estimation: Optional[int] = None


class ProductFilter(BaseModel):
    description: Optional[str] = None
    tags_include: List[str] = Field(alias="tagsInclude")
    tags_exclude: List[str] = Field(alias="tagsExclude")


class ProductGroupChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    code: Optional[str] = None
    description: Optional[Any] = None
    estimation: Optional[int] = None


class ProductsOrder(BaseModel):
    field: ProductsOrderField
    ascending: bool


class ProductsStageFilter(BaseModel):
    project_id: Any = Field(alias="projectId")
    products: List[Any]


class ProjectAdd(BaseModel):
    code: str
    title: str
    description: Any
    estimation: Optional[int] = None
    thumbnail: Optional[Upload] = None
    is_non_profit: bool = Field(alias="isNonProfit")
    done_at: Optional[Any] = Field(alias="doneAt", default=None)


class ProjectChange(BaseModel):
    code: Optional[str] = None
    title: Optional[str] = None
    description: Optional[Any] = None
    estimation: Optional[int] = None
    thumbnail: Optional[Upload] = None
    is_non_profit: Optional[bool] = Field(alias="isNonProfit", default=None)
    done_at: Optional[Any] = Field(alias="doneAt", default=None)


class ReportAdd(BaseModel):
    report_date: Any = Field(alias="reportDate")
    task_id: Any = Field(alias="taskId")
    user_id: Any = Field(alias="userId")
    spent_hours: int = Field(alias="spentHours")


class ReportChange(BaseModel):
    spent_hours: int = Field(alias="spentHours")


class ReportInput(BaseModel):
    report_date: Any = Field(alias="reportDate")
    task_id: Any = Field(alias="taskId")
    user_id: Any = Field(alias="userId")


class ReportsInput(BaseModel):
    report_date_from: Optional[Any] = Field(alias="reportDateFrom", default=None)
    report_date_to: Optional[Any] = Field(alias="reportDateTo", default=None)
    task_ids: Optional[List[Any]] = Field(alias="taskIds", default=None)
    user_ids: Optional[List[Any]] = Field(alias="userIds", default=None)


class ReportsOrder(BaseModel):
    field: ReportsOrderField
    ascending: bool


class StringsAddRemove(BaseModel):
    add: List[str]
    remove: List[str]


class StringsUpdate(BaseModel):
    set: Optional[List[str]] = None
    add_remove: Optional["StringsAddRemove"] = Field(alias="addRemove", default=None)


class TaskAdd(BaseModel):
    project_id: Any = Field(alias="projectId")
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: str
    description: Any
    estimation: Optional[int] = None
    priority: Optional[int] = None
    users: List[Any]
    products: List[Any]
    tags: List[str]


class TaskAssignAction(BaseModel):
    start_work: Optional[Any] = Field(alias="startWork", default=None)
    stop_work: Optional[int] = Field(alias="stopWork", default=None)


class TaskBoardFilter(BaseModel):
    project_id: Any = Field(alias="projectId")
    chunks: List[Any]
    products: List[Any]


class TaskChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: Optional[str] = None
    description: Optional[Any] = None
    estimation: Optional[int] = None
    priority: Optional[int] = None
    users: Optional["UuidsUpdate"] = None
    products: Optional[List[Any]] = None
    tags: Optional["StringsUpdate"] = None


class TaskGroupAdd(BaseModel):
    project_id: Any = Field(alias="projectId")
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: str
    description: Any
    priority: Optional[int] = None
    estimation: Optional[int] = None


class TaskGroupChange(BaseModel):
    parent_id: Optional[Any] = Field(alias="parentId", default=None)
    title: Optional[str] = None
    description: Optional[Any] = None
    priority: Optional[int] = None
    estimation: Optional[int] = None


class TeamChange(BaseModel):
    name: Optional[str] = None
    is_deleted: Optional[bool] = Field(alias="isDeleted", default=None)
    users: Optional[List[Any]] = None


class UserChange(BaseModel):
    name: Optional[str] = None
    role: Optional[UserRole] = None
    avatar: Optional[Upload] = None
    is_deleted: Optional[bool] = Field(alias="isDeleted", default=None)
    team_id: Optional[Any] = Field(alias="teamId", default=None)
    timezone: Optional[str] = None
    is_production: Optional[bool] = Field(alias="isProduction", default=None)


class UuidsAddRemove(BaseModel):
    add: List[Any]
    remove: List[Any]


class UuidsUpdate(BaseModel):
    set: Optional[List[Any]] = None
    add_remove: Optional["UuidsAddRemove"] = Field(alias="addRemove", default=None)


EpicChange.model_rebuild()
PostsInputPagination.model_rebuild()
ProductChange.model_rebuild()
StringsUpdate.model_rebuild()
TaskChange.model_rebuild()
UuidsUpdate.model_rebuild()
