# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any

from .base_model import BaseModel


class Login(BaseModel):
    login: "LoginLogin"


class LoginLogin(BaseModel):
    id: Any
    nbf: Any
    exp: Any


Login.model_rebuild()
