# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class PostCreateBlind(BaseModel):
    post_create_blind: Any = Field(alias="postCreateBlind")
