# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any

from pydantic import Field

from .base_model import BaseModel


class ProductCreate(BaseModel):
    product_create: "ProductCreateProductCreate" = Field(alias="productCreate")


class ProductCreateProductCreate(BaseModel):
    id: Any


ProductCreate.model_rebuild()
