# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List

from .base_model import BaseModel


class Projects(BaseModel):
    projects: List["ProjectsProjects"]


class ProjectsProjects(BaseModel):
    id: Any
    code: str
    title: str


Projects.model_rebuild()
