# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ProductStatusEnum


class UpdateProducts(BaseModel):
    products_update: List["UpdateProductsProductsUpdate"] = Field(
        alias="productsUpdate"
    )


class UpdateProductsProductsUpdate(BaseModel):
    id: Any
    code: str
    status: Optional[ProductStatusEnum]
    due_to: Optional[Any] = Field(alias="dueTo")
    estimation: Optional[int]
    deliverable: Optional[bool]
    description: Optional[Any]
    tags: List[str]
    thumbnail: Optional[str]


UpdateProducts.model_rebuild()
