# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel


class WhoAmI(BaseModel):
    whoami: Optional["WhoAmIWhoami"]


class WhoAmIWhoami(BaseModel):
    id: Any
    nbf: Any
    exp: Any


WhoAmI.model_rebuild()
