# Generated by ariadne-codegen
# Source: queries.graphql

from typing import Any, Optional

from .base_model import BaseModel


class Whoami(BaseModel):
    whoami: Optional["WhoamiWhoami"]


class WhoamiWhoami(BaseModel):
    id: Any


Whoami.model_rebuild()
